version: "3.9"

services:
    api:
        build: ./api
        volumes:
            - ./api:/app
        secrets:
            - mysql_password
        depends_on:
            - db

    db:
        image: mysql:latest
        volumes:
            - mysqldata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD='yes'

volumes:
    mysqldata:

secrets:
    mysql_password:
        file: ./mysql_password.txt
