version: "3.9"

services:
    api:
        build: ./api
        volumes:
            - ./api:/app
        secrets:
            - mysql_password
        depends_on:
            - db

    db:
        build: ./db
        volumes:
            - mysqldata:/var/lib/mysql
        secrets:
            - mysql_password

volumes:
    mysqldata:

secrets:
    mysql_password:
        file: ./mysql_password.txt
