version: "3.9"

services:
    api:
        build: ./api
        volumes:
            - ./api:/app

        depends_on:
            - db

    db:
        image: mysql:latest
        volumes:
            - mysqldata:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD='1'

volumes:
    mysqldata:
